/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ComboController;
import controller.FOPController;
import controller.MaterialController;
import controller.ProductController;
import controller.PromotionController;
import controller.RecipeController;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.FOP;
import model.Material;
import model.Product;
import model.Promotion;
import model.Recipe;
import util.AppUtil;

/**
 *
 * @author Admin
 */
public class JPanelWarehouse extends javax.swing.JPanel {

    /**
     * Creates new form JPanelWarehouse
     */
    private List<String> listDateAdd;
    private String dateAdded;
    private List<Product> productList;
    private List<Product> productListInRecipe;

    public JPanelWarehouse() throws SQLException {
        initComponents();
        showListDateAddedMaterial();
        showListProductInRecipe();
        showAllProductComboBox();
        setViewTable(jTableRecipe);
        setViewTable(jTableAllMaterial);
        setViewTable(jTableMaterial);
        setViewTable(jTableMaterialRepice);
        setViewTable(jTableProductRecipe);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogEditmaterial = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldRawMaterialIDEdit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldRawMaterialNameEdit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldRawMaterialAmountEdit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldRawMaterialPriceEdit = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldUnitEdit = new javax.swing.JTextField();
        jButtonEditMaterial = new javax.swing.JButton();
        jDialogAddMaterial = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableAllMaterial = new javax.swing.JTable();
        jButtonAddMaterialRecipe = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldSL = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jDialogEditRecipe = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabelProductName = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableEditRecipe = new javax.swing.JTable();
        jButtonAddMeterialRecipe = new javax.swing.JButton();
        jButtonDeleteMaterialRecipe = new javax.swing.JButton();
        jButtonEditRecipe = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRawMaterialID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldRawMaterialName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldRawMaterialAmount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldRawMaterialPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDateChooserRawMaterial = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jButtonMaterialAdd = new javax.swing.JButton();
        jButtonMaterialEdit = new javax.swing.JButton();
        jButtonMaterialDelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUnit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMaterial = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListMaterialDateAdd = new javax.swing.JList();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxProduct = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableRecipe = new javax.swing.JTable();
        jButtonAddMaterial = new javax.swing.JButton();
        jButtonDeleteMaterial = new javax.swing.JButton();
        jButtonRecipeAdd = new javax.swing.JButton();
        jButtonRecipeEdit = new javax.swing.JButton();
        jButtonRecipeDelete = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableMaterialRepice = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableProductRecipe = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập Nguyên liệu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(0, 51, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 0, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 204));
        jLabel7.setText("Mã nguyên liệu : ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 204));
        jLabel8.setText("Tên nguyên liệu : ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 204));
        jLabel9.setText("Số lượng :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 204));
        jLabel10.setText("Giá nguyên liệu :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 204));
        jLabel12.setText("Đơn vị tính :");

        jButtonEditMaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEditMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hammer.png"))); // NOI18N
        jButtonEditMaterial.setText("Thực hiện");
        jButtonEditMaterial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditMaterial.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEditMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditMaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldRawMaterialIDEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(jTextFieldRawMaterialNameEdit)
                            .addComponent(jTextFieldRawMaterialAmountEdit)
                            .addComponent(jTextFieldRawMaterialPriceEdit)
                            .addComponent(jTextFieldUnitEdit)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldRawMaterialIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldRawMaterialNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldRawMaterialAmountEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldRawMaterialPriceEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldUnitEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jButtonEditMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialogEditmaterialLayout = new javax.swing.GroupLayout(jDialogEditmaterial.getContentPane());
        jDialogEditmaterial.getContentPane().setLayout(jDialogEditmaterialLayout);
        jDialogEditmaterialLayout.setHorizontalGroup(
            jDialogEditmaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditmaterialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogEditmaterialLayout.setVerticalGroup(
            jDialogEditmaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditmaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jTableAllMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableAllMaterial);

        jButtonAddMaterialRecipe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddMaterialRecipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_order.png"))); // NOI18N
        jButtonAddMaterialRecipe.setText("Thêm");
        jButtonAddMaterialRecipe.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonAddMaterialRecipe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAddMaterialRecipe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAddMaterialRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMaterialRecipeActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 153));
        jLabel13.setText("Số lượng :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 51));
        jLabel18.setText("Nguyên liệu");

        javax.swing.GroupLayout jDialogAddMaterialLayout = new javax.swing.GroupLayout(jDialogAddMaterial.getContentPane());
        jDialogAddMaterial.getContentPane().setLayout(jDialogAddMaterialLayout);
        jDialogAddMaterialLayout.setHorizontalGroup(
            jDialogAddMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogAddMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogAddMaterialLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jDialogAddMaterialLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDialogAddMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogAddMaterialLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldSL, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAddMaterialLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonAddMaterialRecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jDialogAddMaterialLayout.setVerticalGroup(
            jDialogAddMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAddMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialogAddMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialogAddMaterialLayout.createSequentialGroup()
                        .addGroup(jDialogAddMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddMaterialRecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setText("Tên sản phẩm :");

        jLabelProductName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelProductName.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProductName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductName.setText("Hồ lô");

        jTableEditRecipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nguyên liệu", "Tên nguyên liệu", "Số lượng", "Đơn vị tính"
            }
        ));
        jScrollPane7.setViewportView(jTableEditRecipe);

        jButtonAddMeterialRecipe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddMeterialRecipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-icon.png"))); // NOI18N
        jButtonAddMeterialRecipe.setText("Thêm nguyên liệu");
        jButtonAddMeterialRecipe.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonAddMeterialRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMeterialRecipeActionPerformed(evt);
            }
        });

        jButtonDeleteMaterialRecipe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDeleteMaterialRecipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/khong_hop_le2.png"))); // NOI18N
        jButtonDeleteMaterialRecipe.setText("Xóa nguyên liệu");
        jButtonDeleteMaterialRecipe.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonDeleteMaterialRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteMaterialRecipeActionPerformed(evt);
            }
        });

        jButtonEditRecipe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEditRecipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hammer.png"))); // NOI18N
        jButtonEditRecipe.setText("Thực hiện");
        jButtonEditRecipe.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonEditRecipe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditRecipe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEditRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditRecipeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonDeleteMaterialRecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabelProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jButtonAddMeterialRecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonEditRecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProductName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddMeterialRecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteMaterialRecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButtonEditRecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jDialogEditRecipeLayout = new javax.swing.GroupLayout(jDialogEditRecipe.getContentPane());
        jDialogEditRecipe.getContentPane().setLayout(jDialogEditRecipeLayout);
        jDialogEditRecipeLayout.setHorizontalGroup(
            jDialogEditRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditRecipeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogEditRecipeLayout.setVerticalGroup(
            jDialogEditRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditRecipeLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14))
        );

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập Nguyên liệu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(0, 51, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 0, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 204));
        jLabel1.setText("Mã nguyên liệu : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 204));
        jLabel2.setText("Tên nguyên liệu : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 204));
        jLabel3.setText("Số lượng :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 204));
        jLabel4.setText("Giá nguyên liệu :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 204));
        jLabel5.setText("Ngày nhập :");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        jButtonMaterialAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonMaterialAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_nl_32.png"))); // NOI18N
        jButtonMaterialAdd.setText("Nhập");
        jButtonMaterialAdd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonMaterialAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaterialAddActionPerformed(evt);
            }
        });

        jButtonMaterialEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonMaterialEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_32.png"))); // NOI18N
        jButtonMaterialEdit.setText("Sửa");
        jButtonMaterialEdit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonMaterialEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaterialEditActionPerformed(evt);
            }
        });

        jButtonMaterialDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonMaterialDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_32.png"))); // NOI18N
        jButtonMaterialDelete.setText("Xóa");
        jButtonMaterialDelete.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonMaterialDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaterialDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButtonMaterialAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(jButtonMaterialEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonMaterialDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMaterialAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMaterialEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButtonMaterialDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 204));
        jLabel6.setText("Đơn vị tính :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldRawMaterialID)
                    .addComponent(jTextFieldRawMaterialName)
                    .addComponent(jTextFieldRawMaterialAmount)
                    .addComponent(jTextFieldRawMaterialPrice)
                    .addComponent(jDateChooserRawMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jTextFieldUnit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldRawMaterialID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldRawMaterialName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldRawMaterialAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldRawMaterialPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooserRawMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTableMaterial.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jTableMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMaterial);

        jListMaterialDateAdd.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListMaterialDateAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMaterialDateAddMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListMaterialDateAdd);

        jLabel19.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 255));
        jLabel19.setText("Ngày nhập");

        jLabel20.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 255));
        jLabel20.setText("Nguyên liệu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nguyên liệu", jPanel3);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm công thức", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("Sản phẩm :");

        jComboBoxProduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxProduct.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTableRecipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nguyên liệu", "Tên nguyên liệu", "Số lượng", "ĐVT"
            }
        ));
        jScrollPane3.setViewportView(jTableRecipe);

        jButtonAddMaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jButtonAddMaterial.setText("Thêm nguyên liệu");
        jButtonAddMaterial.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonAddMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMaterialActionPerformed(evt);
            }
        });

        jButtonDeleteMaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDeleteMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/khong_hop_le2.png"))); // NOI18N
        jButtonDeleteMaterial.setText("Xóa nguyên liệu");
        jButtonDeleteMaterial.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonDeleteMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteMaterialActionPerformed(evt);
            }
        });

        jButtonRecipeAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRecipeAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_menu_32.png"))); // NOI18N
        jButtonRecipeAdd.setText("Thêm");
        jButtonRecipeAdd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonRecipeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecipeAddActionPerformed(evt);
            }
        });

        jButtonRecipeEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRecipeEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_32.png"))); // NOI18N
        jButtonRecipeEdit.setText("Sửa");
        jButtonRecipeEdit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonRecipeEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecipeEditActionPerformed(evt);
            }
        });

        jButtonRecipeDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRecipeDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel_2.png"))); // NOI18N
        jButtonRecipeDelete.setText("Xóa");
        jButtonRecipeDelete.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonRecipeDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecipeDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonAddMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDeleteMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonRecipeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRecipeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRecipeDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRecipeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRecipeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRecipeDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableMaterialRepice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTableMaterialRepice);

        jTableProductRecipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProductRecipe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductRecipeMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTableProductRecipe);

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 102, 255));
        jLabel16.setText("Sản phẩm");

        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 102, 255));
        jLabel17.setText("Nguyên liệu");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Công thức", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Trang chủ");
        jTabbedPane1.getAccessibleContext().setAccessibleParent(jTabbedPane1);
    }// </editor-fold>//GEN-END:initComponents
 private void setViewTable(JTable jTable) {
        jTable.setRowHeight(30);
        jTable.setShowGrid(true);//viền table
        jTable.setGridColor(Color.gray);//màu viền table
        jTable.setSelectionBackground(new Color(118, 93, 105));
    }

    private void showAllMaterialAdd() throws SQLException {
        jTableAllMaterial.removeAll();
        List<Material> materialList = MaterialController.listMaterialAll();
        String[] arr = {"Mã nguyên liệu", "Tên nguyên liệu", "Số lượng", "ĐVT"};
        DefaultTableModel model = new DefaultTableModel(arr, 0);
        for (Material m : materialList) {
            Vector vector = new Vector();
            vector.add(m.getMaterialID());
            vector.add(m.getMaterialName());
            vector.add(m.getMaterialAmount());
            vector.add(m.getUnit());
            model.addRow(vector);
        }
        jTableAllMaterial.setModel(model);
    }

    private void showListProductInRecipe() throws SQLException {
        jTableProductRecipe.removeAll();
        productListInRecipe = RecipeController.listAllProductInRecipe();
        String[] arr = {"Mã sản phẩm", "Tên sản phẩm"};
        DefaultTableModel model = new DefaultTableModel(arr, 0);
        for (Product p : productListInRecipe) {
            Vector vector = new Vector();
            vector.add(p.getProductID());
            vector.add(p.getProductName());
            model.addRow(vector);
        }
        jTableProductRecipe.setModel(model);
    }

    private void showAllProductComboBox() throws SQLException {
        productList = ProductController.listAllProduct();
        jComboBoxProduct.removeAllItems();
        List<String> productNameInRecipe = new ArrayList<>();
        List<String> AllproductName = new ArrayList<>();
        for (Product p1 : productList) {
            AllproductName.add(p1.getProductName());
        }
        for (Product p2 : productListInRecipe) {
            productNameInRecipe.add(p2.getProductName());
        }
        for (String name : AllproductName) {
            if (!productNameInRecipe.contains(name)) {
                jComboBoxProduct.addItem(name);
            }
        }
    }

    private void showRecipeByProductID(String productID) throws SQLException {
        jTableMaterialRepice.removeAll();
        List<Material> materialList = RecipeController.listMaterialByProductID(productID);
        String[] arr = {"Mã nguyên liệu", "Tên nguyên liệu", "Số lượng", "ĐVT"};
        DefaultTableModel model = new DefaultTableModel(arr, 0);
        for (Material m : materialList) {
            Vector vector = new Vector();
            vector.add(m.getMaterialID());
            vector.add(m.getMaterialName());
            vector.add(m.getAmountInRecipe());
            vector.add(m.getUnit());
            model.addRow(vector);
        }
        jTableMaterialRepice.setModel(model);
    }

    private void jButtonMaterialEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaterialEditActionPerformed
        // TODO add your handling code here:
        int selectRow = jTableMaterial.getSelectedRow();
        TableModel model = jTableMaterial.getModel();
        if (selectRow == -1) {
            JOptionPane.showMessageDialog(null, "Bạn cần phải chọn nguyên liệu cần thay đổi!");
        } else {
            showDialogEditMaterial();
            String id = model.getValueAt(selectRow, 0).toString();
            String name = model.getValueAt(selectRow, 1).toString();
            String amount = model.getValueAt(selectRow, 2).toString();
            String price = model.getValueAt(selectRow, 3).toString();
            String unit = model.getValueAt(selectRow, 5).toString();
            dateAdded = model.getValueAt(selectRow, 4).toString();
            jTextFieldRawMaterialIDEdit.setText(id);
            jTextFieldRawMaterialNameEdit.setText(name);
            jTextFieldRawMaterialPriceEdit.setText(price);
            jTextFieldRawMaterialAmountEdit.setText(amount);
            jTextFieldUnitEdit.setText(unit);
            jTextFieldRawMaterialIDEdit.setEditable(false);
        }
    }//GEN-LAST:event_jButtonMaterialEditActionPerformed

    private void showDialogEditMaterial() {
        jDialogEditmaterial.setVisible(true);
        jDialogEditmaterial.setSize(600, 700);
        jDialogEditmaterial.setAlwaysOnTop(true);
    }

    private void showListDateAddedMaterial() throws SQLException {
        jListMaterialDateAdd.removeAll();
        listDateAdd = MaterialController.listDateAdded();
        DefaultListModel<String> model = new DefaultListModel<>();
        model.addElement("Toàn bộ");
        for (String s : listDateAdd) {
            model.addElement(s);
        }
        jListMaterialDateAdd.setModel(model);
    }

    private void showListMaterialAll() {
        jTableMaterial.removeAll();
        String[] arr = {"Mã nguyên liệu", "Tên nguyên liệu", "Số lượng", "Giá", "Ngày nhập", "ĐVT"};
        DefaultTableModel model = new DefaultTableModel(arr, 0);
        List<Material> materialList = new ArrayList<>();
        try {
            materialList = MaterialController.listMaterialAll();
        } catch (SQLException ex) {
            Logger.getLogger(JPanelSale.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Material m : materialList) {
            Vector vector = new Vector();
            vector.add(m.getMaterialID());
            vector.add(m.getMaterialName());
            vector.add(m.getMaterialAmount());
            vector.add(m.getMaterialPrice());
            vector.add(m.getMaterialDateAdd());
            vector.add(m.getUnit());
            model.addRow(vector);
        }
        jTableMaterial.setModel(model);
    }

    private void showListMaterialByDateAdd(String date) {
        jTableMaterial.removeAll();
        String[] arr = {"Mã nguyên liệu", "Tên nguyên liệu", "Số lượng", "Giá", "Ngày nhập", "ĐVT"};
        DefaultTableModel model = new DefaultTableModel(arr, 0);
        List<Material> materialList = new ArrayList<>();
        try {
            materialList = MaterialController.listMaterialByDateAdded(date);
        } catch (SQLException ex) {
            Logger.getLogger(JPanelSale.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Material m : materialList) {
            Vector vector = new Vector();
            vector.add(m.getMaterialID());
            vector.add(m.getMaterialName());
            vector.add(m.getMaterialAmount());
            vector.add(m.getMaterialPrice());
            vector.add(m.getMaterialDateAdd());
            vector.add(m.getUnit());
            model.addRow(vector);
        }
        jTableMaterial.setModel(model);
    }

    private void jButtonMaterialAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaterialAddActionPerformed
        // TODO add your handling code here:
        String materialID = jTextFieldRawMaterialID.getText();
        String materialname = jTextFieldRawMaterialName.getText();
        String dateAdded = AppUtil.format(jDateChooserRawMaterial.getDate());
        String unit = jTextFieldUnit.getText();
        if (materialID.equals("") || materialname.equals("") || unit.equals("")) {
            JOptionPane.showMessageDialog(null, "Xin vui nhập đầy đủ thông tin!");
        } else {
            try {
                int amount = Integer.parseInt(jTextFieldRawMaterialAmount.getText());
                int price = Integer.parseInt(jTextFieldRawMaterialPrice.getText());
                Material material = new Material(materialID, materialname, dateAdded, price, amount, unit);
                MaterialController.insertMaterial(material);
                JOptionPane.showMessageDialog(null, "Thêm thành công!");
                showListDateAddedMaterial();
                showListMaterialAll();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Bạn cần phải nhập số vào ô số lượng và giá nguyên liệu, xin vui lòng nhập lại");
            } catch (SQLException ex) {
                Logger.getLogger(JPanelWarehouse.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Thêm không thành công, xin vui lòng thử lại!");
            }
        }
    }//GEN-LAST:event_jButtonMaterialAddActionPerformed

    private void jListMaterialDateAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMaterialDateAddMouseClicked
        // TODO add your handling code here:
        showListMaterialBySelectTableDate();
    }//GEN-LAST:event_jListMaterialDateAddMouseClicked

    private void showListMaterialBySelectTableDate() {
        String valueSelect = jListMaterialDateAdd.getSelectedValue().toString();
        int selectIndex = jListMaterialDateAdd.getSelectedIndex();
        if (selectIndex == 0) {
            showListMaterialAll();
        } else if (selectIndex > 0) {
            showListMaterialByDateAdd(valueSelect);
        }
    }

    private void jButtonEditMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditMaterialActionPerformed
        // TODO add your handling code here:
        String id = jTextFieldRawMaterialIDEdit.getText();
        String name = jTextFieldRawMaterialNameEdit.getText();
        String unit = jTextFieldUnitEdit.getText();
        try {
            int amount = Integer.parseInt(jTextFieldRawMaterialAmountEdit.getText());
            int price = Integer.parseInt(jTextFieldRawMaterialPriceEdit.getText());
            if (name.equals("") || unit.equals("")) {
                JOptionPane.showMessageDialog(null, "Bạn cần phải nhập đầy đủ thông tin");
            } else {
                MaterialController.updateMaterial(new Material(id, name, dateAdded, price, amount, unit));
                JOptionPane.showMessageDialog(null, "Cập nhật thành công!");
                showListMaterialBySelectTableDate();
            }
        } catch (NumberFormatException exception) {
            JOptionPane.showMessageDialog(null, "Bạn cần phải nhập số vào ô số lượng hoặc giá nguyên liệu!");
        } catch (SQLException ex) {
            Logger.getLogger(JPanelWarehouse.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Cập nhật không thành công, xin vui lòng thử lại!");
        }
    }//GEN-LAST:event_jButtonEditMaterialActionPerformed

    private void jButtonMaterialDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaterialDeleteActionPerformed
        // TODO add your handling code here:
        int select = jTableMaterial.getSelectedRow();
        TableModel model = jTableMaterial.getModel();
        String id = model.getValueAt(select, 0).toString();
        String date = model.getValueAt(select, 4).toString();
        if (select == -1) {
            JOptionPane.showMessageDialog(null, "Bạn phải chọn nguyên liệu cần xóa!");
        } else {
            int rs = JOptionPane.showConfirmDialog(null, "Bạn có chắn chắn muốn xóa không?");
            if (rs == 0) {
                try {
                    MaterialController.deleteMaterial(id, date);
                    JOptionPane.showMessageDialog(null, "Xóa thành công!");
                    showListMaterialBySelectTableDate();
                } catch (SQLException ex) {
                    Logger.getLogger(JPanelWarehouse.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Xóa không thành công, xin vui lòng thử lại!");
                }
            }
        }
    }//GEN-LAST:event_jButtonMaterialDeleteActionPerformed

    private void jButtonRecipeEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecipeEditActionPerformed
        // TODO add your handling code here:
        int select = jTableProductRecipe.getSelectedRow();
        TableModel model = jTableProductRecipe.getModel();
        String productName = model.getValueAt(select, 1).toString();
        String productID = model.getValueAt(select, 0).toString();
        if (select == -1) {
            JOptionPane.showMessageDialog(null, "Bạn cần phải chọn sản phẩm muốn sửa!");
        } else {
            try {
                showDialogEditRecipe();
                jLabelProductName.setText(productName);
                List<Material> materialList = RecipeController.listMaterialByProductID(productID);
                DefaultTableModel defaultTableModel = (DefaultTableModel) jTableEditRecipe.getModel();
                int sumRow = defaultTableModel.getRowCount();
                for (int i = sumRow - 1; i >= 0; i--) {
                    defaultTableModel.removeRow(i);
                }
                for (Material m : materialList) {
                    defaultTableModel.addRow(new Object[]{m.getMaterialID(), m.getMaterialName(), m.getAmountInRecipe(), m.getUnit()});
                }
            } catch (SQLException ex) {
                Logger.getLogger(JPanelWarehouse.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonRecipeEditActionPerformed

    private void showDialogEditRecipe() {
        jDialogEditRecipe.setVisible(true);
        jDialogEditRecipe.setSize(600, 700);
        jDialogEditRecipe.setAlwaysOnTop(true);
    }

    private void jButtonRecipeDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecipeDeleteActionPerformed
        // TODO add your handling code here:
        int select = jTableProductRecipe.getSelectedRow();
        TableModel model = jTableProductRecipe.getModel();
        String productID = model.getValueAt(select, 0).toString();
        if (select == -1) {
            JOptionPane.showMessageDialog(null, "Bạn cần phải chọn sản phẩm muốn xóa!");
        } else {
            int rs = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa.");
            if (rs == 0) {
                try {
                    RecipeController.deleteRecipe(productID);
                    JOptionPane.showMessageDialog(null, "Xóa thành công!");
                    showListProductInRecipe();
                    showAllProductComboBox();
                    jTableMaterialRepice.removeAll();
                } catch (SQLException ex) {
                    Logger.getLogger(JPanelWarehouse.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Xóa không thành công xin vui lòng thử lại!");
                }
            }
        }
    }//GEN-LAST:event_jButtonRecipeDeleteActionPerformed

    private void jTableProductRecipeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductRecipeMouseClicked
        // TODO add your handling code here:
        int select = jTableProductRecipe.getSelectedRow();
        TableModel tableModel = jTableProductRecipe.getModel();
        String productID = tableModel.getValueAt(select, 0).toString();
        if (select >= 0) {
            try {
                showRecipeByProductID(productID);
            } catch (SQLException ex) {
                Logger.getLogger(JPanelWarehouse.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTableProductRecipeMouseClicked

    private void jButtonAddMaterialRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMaterialRecipeActionPerformed
        // TODO add your handling code here:
        int select = jTableAllMaterial.getSelectedRow();
        if (select == -1) {
            JOptionPane.showMessageDialog(null, "Bạn phải chọn nguyên liệu cần thêm vào");
        } else {
            TableModel model = jTableAllMaterial.getModel();
            try {
                int SL = Integer.parseInt(jTextFieldSL.getText());
                DefaultTableModel modelRecipe = (DefaultTableModel) jTableRecipe.getModel();
                DefaultTableModel modelEditRecipe = (DefaultTableModel) jTableEditRecipe.getModel();
                if (jDialogEditRecipe.isVisible()) {
                    modelEditRecipe.addRow(new Object[]{model.getValueAt(select, 0).toString(), model.getValueAt(select, 1).toString(), SL, model.getValueAt(select, 3).toString()});
                } else {
                    modelRecipe.addRow(new Object[]{model.getValueAt(select, 0).toString(), model.getValueAt(select, 1).toString(), SL, model.getValueAt(select, 3).toString()});
                }
                jDialogAddMaterial.setVisible(false);
            } catch (NumberFormatException exception) {
                JOptionPane.showMessageDialog(null, "Số lượng bạn nhập không đúng, xin vui lòng nhập lại!");
            }
        }
    }//GEN-LAST:event_jButtonAddMaterialRecipeActionPerformed

    private void jButtonAddMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMaterialActionPerformed
        // TODO add your handling code here:
        jDialogAddMaterial.setVisible(true);
        jDialogAddMaterial.setAlwaysOnTop(true);
        jDialogAddMaterial.setSize(800, 500);
        try {
            showAllMaterialAdd();
        } catch (SQLException ex) {
            Logger.getLogger(JPanelWarehouse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAddMaterialActionPerformed

    private void jButtonRecipeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecipeAddActionPerformed
        // TODO add your handling code here:
        String productName = jComboBoxProduct.getSelectedItem().toString();
        TableModel model = jTableRecipe.getModel();
        int sumRow = jTableRecipe.getRowCount();
        String productID = null;
        for (Product p : productList) {
            if (productName.equals(p.getProductName())) {
                productID = p.getProductID();
            }
        }
        if (sumRow > 0) {
            try {
                for (int i = 0; i < sumRow; i++) {
                    RecipeController.insertRecipe(new Recipe(productID, model.getValueAt(i, 0).toString(), (int) model.getValueAt(i, 2)));
                }
                JOptionPane.showMessageDialog(null, "Thêm thành công!");
                showListProductInRecipe();
                showAllProductComboBox();
                jDialogEditRecipe.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(JPanelWarehouse.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Thêm không thành công,xin vui lòng thử lại!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bạn chưa điền đầy đủ thông tin,xin vui lòng kiểm tra lại");
        }
    }//GEN-LAST:event_jButtonRecipeAddActionPerformed

    private void jButtonDeleteMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteMaterialActionPerformed
        // TODO add your handling code here:
        int row = jTableRecipe.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Bạn cần phải chọn sản phẩm muốn xóa!");
        } else {
            ((DefaultTableModel) jTableRecipe.getModel()).removeRow(row);
        }
    }//GEN-LAST:event_jButtonDeleteMaterialActionPerformed

    private void jButtonDeleteMaterialRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteMaterialRecipeActionPerformed
        // TODO add your handling code here:
        int row = jTableEditRecipe.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Bạn cần phải chọn sản phẩm muốn xóa!");
        } else {
            ((DefaultTableModel) jTableEditRecipe.getModel()).removeRow(row);
        }
    }//GEN-LAST:event_jButtonDeleteMaterialRecipeActionPerformed

    private void jButtonAddMeterialRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMeterialRecipeActionPerformed
        // TODO add your handling code here:
        jDialogAddMaterial.setVisible(true);
        jDialogAddMaterial.setAlwaysOnTop(true);
        jDialogAddMaterial.setSize(800, 700);
        try {
            showAllMaterialAdd();
        } catch (SQLException ex) {
            Logger.getLogger(JPanelWarehouse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAddMeterialRecipeActionPerformed

    private void jButtonEditRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditRecipeActionPerformed
        // TODO add your handling code here:
        String productName = jLabelProductName.getText();
        TableModel model = jTableEditRecipe.getModel();
        int sumRow = jTableEditRecipe.getRowCount();
        String productID = null;
        for (Product p : productList) {
            if (productName.equals(p.getProductName())) {
                productID = p.getProductID();
            }
        }
        if (sumRow > 0) {
            try {
                RecipeController.deleteRecipe(productID);
                for (int i = 0; i < sumRow; i++) {
                    RecipeController.insertRecipe(new Recipe(productID, model.getValueAt(i, 0).toString(), (int) model.getValueAt(i, 2)));
                }
                JOptionPane.showMessageDialog(null, "chỉnh sửa thành công!");
                showListProductInRecipe();
                showAllProductComboBox();
                jDialogEditRecipe.setVisible(true);
                jDialogEditRecipe.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(JPanelWarehouse.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Chỉnh sửa không thành công,xin vui lòng thử lại!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bạn chưa điền đầy đủ thông tin,xin vui lòng kiểm tra lại");
        }
    }//GEN-LAST:event_jButtonEditRecipeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddMaterial;
    private javax.swing.JButton jButtonAddMaterialRecipe;
    private javax.swing.JButton jButtonAddMeterialRecipe;
    private javax.swing.JButton jButtonDeleteMaterial;
    private javax.swing.JButton jButtonDeleteMaterialRecipe;
    private javax.swing.JButton jButtonEditMaterial;
    private javax.swing.JButton jButtonEditRecipe;
    private javax.swing.JButton jButtonMaterialAdd;
    private javax.swing.JButton jButtonMaterialDelete;
    private javax.swing.JButton jButtonMaterialEdit;
    private javax.swing.JButton jButtonRecipeAdd;
    private javax.swing.JButton jButtonRecipeDelete;
    private javax.swing.JButton jButtonRecipeEdit;
    private javax.swing.JComboBox jComboBoxProduct;
    private com.toedter.calendar.JDateChooser jDateChooserRawMaterial;
    private javax.swing.JDialog jDialogAddMaterial;
    private javax.swing.JDialog jDialogEditRecipe;
    private javax.swing.JDialog jDialogEditmaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelProductName;
    private javax.swing.JList jListMaterialDateAdd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableAllMaterial;
    private javax.swing.JTable jTableEditRecipe;
    private javax.swing.JTable jTableMaterial;
    private javax.swing.JTable jTableMaterialRepice;
    private javax.swing.JTable jTableProductRecipe;
    private javax.swing.JTable jTableRecipe;
    private javax.swing.JTextField jTextFieldRawMaterialAmount;
    private javax.swing.JTextField jTextFieldRawMaterialAmountEdit;
    private javax.swing.JTextField jTextFieldRawMaterialID;
    private javax.swing.JTextField jTextFieldRawMaterialIDEdit;
    private javax.swing.JTextField jTextFieldRawMaterialName;
    private javax.swing.JTextField jTextFieldRawMaterialNameEdit;
    private javax.swing.JTextField jTextFieldRawMaterialPrice;
    private javax.swing.JTextField jTextFieldRawMaterialPriceEdit;
    private javax.swing.JTextField jTextFieldSL;
    private javax.swing.JTextField jTextFieldUnit;
    private javax.swing.JTextField jTextFieldUnitEdit;
    // End of variables declaration//GEN-END:variables
}
