/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ConnectionDB;
import controller.ProductController;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Product;

/**
 *
 * @author hoang
 */
public class JPanelProduct extends javax.swing.JPanel {

    private DefaultTableModel tblModel;

    /**
     * Creates new form JPanelSanpham
     */
    public JPanelProduct() throws SQLException, ClassNotFoundException {
        initComponents();
        showDataProductType();
        showDataProduct();
        showAllTypeProductComboBox();
        tblModel = (DefaultTableModel) jTableProductType.getModel();
        setViewTable(jTableProduct);
        setViewTable(jTableProductType);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtProductTypeID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtProductTypeName = new javax.swing.JTextField();
        btnDialogType = new javax.swing.JButton();
        btnSkipDialog = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtProductTypeID1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtProductTypeName1 = new javax.swing.JTextField();
        btnDialogType1 = new javax.swing.JButton();
        btnSkipDialog1 = new javax.swing.JButton();
        jDialog3 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtProductName3 = new javax.swing.JTextField();
        txtAmountRemaining3 = new javax.swing.JTextField();
        txtPrice3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnAdd3 = new javax.swing.JButton();
        btnSkip3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jDialog4 = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtProductName4 = new javax.swing.JTextField();
        txtAmountRemaining4 = new javax.swing.JTextField();
        txtPrice4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnEdit4 = new javax.swing.JButton();
        btnSkip4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAddType = new javax.swing.JButton();
        btnEditType = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductType = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProduct = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        btnEditProduct = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 204));
        jLabel5.setText("NHẬP ĐẦY ĐỦ CÁC THÔNG TIN :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 204));
        jLabel6.setText("LOẠI SP");

        txtProductTypeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductTypeIDActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 204));
        jLabel7.setText("TÊN MÃ SP");

        btnDialogType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_menu_32.png"))); // NOI18N
        btnDialogType.setText("THÊM");
        btnDialogType.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDialogType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDialogTypeActionPerformed(evt);
            }
        });

        btnSkipDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        btnSkipDialog.setText("BỎ QUA");
        btnSkipDialog.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSkipDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkipDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtProductTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProductTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnDialogType, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSkipDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel5)
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProductTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSkipDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDialogType, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("SỬA CÁC THÔNG TIN :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 153));
        jLabel9.setText("LOẠI SP");

        txtProductTypeID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductTypeID1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 153));
        jLabel10.setText("TÊN MÃ SP");

        txtProductTypeName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductTypeName1ActionPerformed(evt);
            }
        });

        btnDialogType1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDialogType1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Utilities.png"))); // NOI18N
        btnDialogType1.setText("SỬA");
        btnDialogType1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDialogType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDialogType1ActionPerformed(evt);
            }
        });

        btnSkipDialog1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSkipDialog1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel_2.png"))); // NOI18N
        btnSkipDialog1.setText("BỎ QUA");
        btnSkipDialog1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSkipDialog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkipDialog1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(31, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtProductTypeID1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProductTypeName1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnDialogType1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSkipDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel8)
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductTypeID1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProductTypeName1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDialogType1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSkipDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 204));
        jLabel3.setText("Tên Sản Phẩm");

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 204));
        jLabel11.setText("Loại Sản Phẩm");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 204));
        jLabel12.setText("Số Lượng");

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 204));
        jLabel13.setText("Giá");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 255));
        jLabel14.setText("NHẬP ĐẦY ĐỦ CÁC THÔNG TIN");

        btnAdd3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-icon.png"))); // NOI18N
        btnAdd3.setText("Thêm");
        btnAdd3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd3ActionPerformed(evt);
            }
        });

        btnSkip3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/khong_hop_le2_1.png"))); // NOI18N
        btnSkip3.setText("Bỏ qua");
        btnSkip3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSkip3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkip3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 204));
        jLabel4.setText("Mã Sản Phẩm");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(txtProductName3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(61, 61, 61)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAmountRemaining3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addGap(190, 190, 190)
                                    .addComponent(btnSkip3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(60, 60, 60))))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(61, 61, 61)
                            .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProductName3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmountRemaining3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSkip3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 204));
        jLabel15.setText("Tên Sản Phẩm");

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 204));
        jLabel16.setText("Loại Sản Phẩm");

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 204));
        jLabel17.setText("Số Lượng");

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 204));
        jLabel18.setText("Giá");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("SỬA CÁC THÔNG TIN");

        btnEdit4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEdit4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hammer.png"))); // NOI18N
        btnEdit4.setText("Sửa");
        btnEdit4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEdit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit4ActionPerformed(evt);
            }
        });

        btnSkip4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSkip4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel_2.png"))); // NOI18N
        btnSkip4.setText("Bỏ qua");
        btnSkip4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSkip4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkip4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrice4, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addComponent(txtAmountRemaining4, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addComponent(txtProductName4, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(213, 213, 213))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEdit4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSkip4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProductName4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmountRemaining4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSkip4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách loại sản phẩm");
        jLabel1.setToolTipText("");

        btnAddType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_menu_32.png"))); // NOI18N
        btnAddType.setText("Thêm");
        btnAddType.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAddType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTypeActionPerformed(evt);
            }
        });

        btnEditType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_32.png"))); // NOI18N
        btnEditType.setText("Sửa ");
        btnEditType.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEditType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTypeActionPerformed(evt);
            }
        });

        jTableProductType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên", "Loại"
            }
        ));
        jTableProductType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductTypeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProductType);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAddType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 227, Short.MAX_VALUE)
                        .addComponent(btnEditType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditType, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddType, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên Sản Phẩm", "Số Lượng", "Giá"
            }
        ));
        jTableProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableProduct);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/milktea.png"))); // NOI18N
        jButton5.setText("Hiển thị tất cả các sản phẩm");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnAddProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_order.png"))); // NOI18N
        btnAddProduct.setText("Thêm");
        btnAddProduct.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnEditProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Utilities.png"))); // NOI18N
        btnEditProduct.setText("Sửa");
        btnEditProduct.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEditProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProductActionPerformed(evt);
            }
        });

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private void showDataProductType() throws SQLException, ClassNotFoundException {
        jTableProductType.removeAll();
        String[] arr = {"Mã Loại sản phẩm", "Tên loại sản phẩm"};
        DefaultTableModel model = new DefaultTableModel(arr, 0);
        String query = "select * from dbo.[productType]";
        Connection connection = ConnectionDB.getConnection();
        PreparedStatement ps = connection.prepareStatement(query);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            Vector vector = new Vector();
            vector.add(rs.getString("productTypeID"));
            vector.add(rs.getString("productTypeName"));
            model.addRow(vector);
        }
        jTableProductType.setModel(model);

    }

    private void setViewTable(JTable jTable) {
        jTable.setRowHeight(30);
        jTable.setShowGrid(true);//viền table
        jTable.setGridColor(Color.gray);//màu viền table
        jTable.setSelectionBackground(new Color(118, 93, 105));
    }

    private void showDataProduct() {
        try {
            jTableProduct.removeAll();
            String[] arr = {"Mã sản phẩm", "Tên sản phẩm", "Số Lượng", "Giá"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);
            String query = "select p.productName,p.productID,p.amountRemaining,p.price from products p INNER JOIN productType t ON p.productTypeID=t.productTypeID";
            Connection connection = ConnectionDB.getConnection();
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector vector = new Vector();
                vector.add(rs.getString("productID"));
                vector.add(rs.getString("productName"));
                vector.add(rs.getInt("amountRemaining"));
                vector.add(rs.getInt("price"));
                model.addRow(vector);
            }
            jTableProduct.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(JPanelOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void showDataProductTypeClick(String valueSelected) {
        try {
            jTableProduct.removeAll();
            String[] arr = {"Mã sản phẩm", "Tên Sản Phẩm", "Số Lượng", "Giá"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);
            String query = "select p.productID ,p.productName,p.amountRemaining,p.price \n"
                    + "from products p JOIN productType pt ON p.productTypeID=pt.productTypeID where pt.productTypeName = ?";
            Connection connection = ConnectionDB.getConnection();
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, valueSelected);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                Vector vector = new Vector();
                vector.add(rs.getString("productID"));
                vector.add(rs.getString("productName"));
                vector.add(rs.getInt("amountRemaining"));
                vector.add(rs.getInt("price"));
                model.addRow(vector);
            }
            jTableProduct.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(JPanelOrder.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private boolean checkTrungTypeID() {
        try {
            Connection connection = ConnectionDB.getConnection();
            String query = "SELECT * FROM dbo.[productType] WHERE productTypeID = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, txtProductTypeID.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                return true;
            }
            ConnectionDB.closeConnection(connection);
        } catch (SQLException ex) {
            Logger.getLogger(JPanelProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }


    private void btnEditProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProductActionPerformed
        // TODO add your handling code here:
        int i = jTableProduct.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn Sản Phẩm nào!");
        } else {
            jDialog4.setSize(600, 600);
            jDialog4.setAlwaysOnTop(true);
            jDialog4.setVisible(true);
        }

    }//GEN-LAST:event_btnEditProductActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
        jDialog3.setSize(600, 600);
        jDialog3.setAlwaysOnTop(true);
        jDialog3.setVisible(true);

    }//GEN-LAST:event_btnAddProductActionPerformed

    private void jTableProductTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductTypeMouseClicked
        // TODO add your handling code here:
        int i = jTableProductType.getSelectedRow();
        String value = jTableProductType.getValueAt(i, 1).toString();
        String value1 = jTableProductType.getValueAt(i, 0).toString();
        showDataProductTypeClick(value);
        txtProductTypeName1.setText(value);
        txtProductTypeID1.setText(value1);


    }//GEN-LAST:event_jTableProductTypeMouseClicked

    private void btnAddTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTypeActionPerformed
        // TODO add your handling code here:
        jDialog1.setSize(700, 400);
        jDialog1.setAlwaysOnTop(true);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_btnAddTypeActionPerformed

    private void btnDialogTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDialogTypeActionPerformed
        // TODO add your handling code here:
        if (txtProductTypeID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Mã Loại SP không được để trống");
            txtProductTypeID.requestFocus();
            return;
        } else if (txtProductTypeName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tên Loại không được để trống");
            txtProductTypeName.requestFocus();
            return;
        }
        String typeId = txtProductTypeID.getText();
        if (typeId.length() != 4) {
            JOptionPane.showMessageDialog(null, "Mã loại SP phải có 4 kí tự ");
            txtProductTypeID.requestFocus();
            return;
        }
        boolean b1 = Character.isLetter(typeId.charAt(0));
        boolean b2 = Character.isLetter(typeId.charAt(1));
        boolean b3 = Character.isDigit(typeId.charAt(2));
        boolean b4 = Character.isDigit(typeId.charAt(3));
        if ((b1 && b2 && b3 && b4) == false) {
            JOptionPane.showMessageDialog(null, "Mã loại Sản Phẩm không đúng. Mẫu: PT01 ");
            txtProductTypeID.requestFocus();
            return;
        }
        if (checkTrungTypeID() == true) {
            JOptionPane.showMessageDialog(null, "Mã Loại SP đã tồn tại!");
            txtProductTypeID.requestFocus();
            return;
        } else {
            try {
                Connection connection = ConnectionDB.getConnection();
                String query = "INSERT INTO dbo.productType(productTypeID,productTypeName)"
                        + "VALUES(?,?)";
                PreparedStatement ps = connection.prepareStatement(query);
                ps.setString(1, txtProductTypeID.getText());
                ps.setString(2, txtProductTypeName.getText());
                ps.executeUpdate();
                try {
                    showDataProductType();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(JPanelProduct.class.getName()).log(Level.SEVERE, null, ex);
                }
                ConnectionDB.closeConnection(connection);
                JOptionPane.showMessageDialog(null, "Thêm thành công");
                txtProductTypeID.setText("");
                txtProductTypeName.setText("");
                showAllTypeProductComboBox();
                jDialog1.setVisible(false);
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDialogTypeActionPerformed

    private void btnDialogType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDialogType1ActionPerformed
        // TODO add your handling code here:
        int i = jTableProductType.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn Loại SP nào!");
        } else {
            try {
                //            PreparedStatement ps = cnt.prepareStatement("UPDATE NhanVien SET HoTen =? ,SoDienThoai=?,DiaChi=?,NgayVaoLam=?,Luong=? WHERE MaNV=?");
                Connection cnn = ConnectionDB.getConnection();
                int row = jTableProductType.getSelectedRow();
                String value = (jTableProductType.getModel().getValueAt(row, 0).toString());
                String query = "UPDATE productType SET productTypeName =? WHERE productTypeID=?";
                PreparedStatement ps = cnn.prepareStatement(query);
                ps.setString(1, txtProductTypeName1.getText());

                //ps.setString(6, tfMaNV.getText());
                if (txtProductTypeID1.getText().equals(value) == false) {
                    ps.setString(2, txtProductTypeID1.getText());
                } else {
                    ps.setString(2, value);
                }//////??????????????
                ps.executeUpdate();
                DefaultTableModel model = (DefaultTableModel) jTableProductType.getModel();
                model.setRowCount(0);
                showDataProductType();
                // jButtonLamMoi.set();
                txtProductTypeID1.setText("");
                txtProductTypeName1.setText("");
                JOptionPane.showMessageDialog(null, "Sửa Loại SP thành công!");
            } catch (SQLException ex) {
                Logger.getLogger(JPanelProduct.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(JPanelProduct.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDialogType1ActionPerformed

    private void btnEditTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTypeActionPerformed
        // TODO add your handling code here:
        int i = jTableProductType.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn Loại SP nào!");
        } else {
            jDialog2.setSize(700, 400);
            jDialog2.setAlwaysOnTop(true);
            jDialog2.setVisible(true);
        }


    }//GEN-LAST:event_btnEditTypeActionPerformed

    private void txtProductTypeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductTypeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductTypeIDActionPerformed

    private void btnSkipDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkipDialogActionPerformed
        // TODO add your handling code here:
        jDialog1.setVisible(false);
    }//GEN-LAST:event_btnSkipDialogActionPerformed

    private void txtProductTypeID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductTypeID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductTypeID1ActionPerformed

    private void txtProductTypeName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductTypeName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductTypeName1ActionPerformed

    private void btnSkipDialog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkipDialog1ActionPerformed
        // TODO add your handling code here:
        jDialog2.setVisible(false);
    }//GEN-LAST:event_btnSkipDialog1ActionPerformed
    private boolean checkTrungProductName() {
        try {
            Connection connection = ConnectionDB.getConnection();
            String query = "SELECT * FROM dbo.[products] WHERE productName = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, txtProductName3.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                return true;
            }
            ConnectionDB.closeConnection(connection);
        } catch (SQLException ex) {
            Logger.getLogger(JPanelProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    private void btnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd3ActionPerformed
        // TODO add your handling code here:
        if (txtProductID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Mã Sản Phẩm không được để trống");
            txtProductID.requestFocus();
            return;
        } else if (txtProductName3.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tên Sản Phẩm không được để trống");
            txtProductName3.requestFocus();
            return;
        } else if (txtAmountRemaining3.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Số lượng không được để trống");
            txtAmountRemaining3.requestFocus();
            return;
        } else if (txtPrice3.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Giá không được để trống");
            txtPrice3.requestFocus();
            return;
        }
        if (checkTrungProductName() == true) {
            JOptionPane.showMessageDialog(null, "Tên Sản Phẩm đã tồn tại!");
            txtProductName3.requestFocus();
            return;
        } else {
            try {
                int type = jComboBox2.getSelectedIndex();
                Connection connection = ConnectionDB.getConnection();
                String query = "insert into products(productID,productName,productTypeID,amountRemaining,price)\n"
                        + "values(?,?,?,?,?)";
                PreparedStatement ps = connection.prepareStatement(query);
                ps.setString(1, txtProductID.getText());
                ps.setString(2, txtProductName3.getText());
                if (type == 0) {
                    ps.setString(3, "PT02");
                } else if (type == 1) {
                    ps.setString(3, "PT03");
                } else {
                    ps.setString(3, "PT01");
                }
                ps.setString(4, txtAmountRemaining3.getText());
                ps.setString(5, txtPrice3.getText());
                ps.executeUpdate();
                showDataProduct();
                ConnectionDB.closeConnection(connection);
                JOptionPane.showMessageDialog(null, "Thêm thành công");
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnAdd3ActionPerformed

    private void btnEdit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit4ActionPerformed
        // TODO add your handling code here:
        int i = jTableProduct.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn SP nào!");
        } else {
            try {
                //            PreparedStatement ps = cnt.prepareStatement("UPDATE NhanVien SET HoTen =? ,SoDienThoai=?,DiaChi=?,NgayVaoLam=?,Luong=? WHERE MaNV=?");
                Connection cnn = ConnectionDB.getConnection();
                int row = jTableProduct.getSelectedRow();
                int type = jComboBox1.getSelectedIndex();
                String value = (jTableProduct.getModel().getValueAt(row, 0).toString());
                String query = "UPDATE products SET productName =? ,productTypeID=?,amountRemaining=?,price=? WHERE productID=?";
                PreparedStatement ps = cnn.prepareStatement(query);
                ps.setString(1, txtProductName4.getText());
                if (type == 0) {
                    ps.setString(2, "PT02");
                } else if (type == 1) {
                    ps.setString(2, "PT03");
                } else {
                    ps.setString(2, "PT01");
                }
                ps.setString(3, txtAmountRemaining4.getText());
                ps.setString(4, txtPrice4.getText());
                ps.setString(5, layProductID(value));

                ps.executeUpdate();
                DefaultTableModel model = (DefaultTableModel) jTableProduct.getModel();
                model.setRowCount(0);
                showDataProduct();
                JOptionPane.showMessageDialog(null, "Sửa SP thành công!");
            } catch (SQLException ex) {
                Logger.getLogger(JPanelProduct.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEdit4ActionPerformed

    private String layProductID(String value) {
        String id = "";
        try {
            Connection cnn = ConnectionDB.getConnection();
            String query = "SELECT productID FROM products WHERE productName = ? ";
            PreparedStatement ps = cnn.prepareStatement(query);
            ps.setString(1, value);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                id = rs.getString("productID");
            }
        } catch (SQLException ex) {
            Logger.getLogger(JPanelOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }

    private void jTableProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductMouseClicked
        // TODO add your handling code here:
        int i = jTableProduct.getSelectedRow();
        String value = jTableProduct.getValueAt(i, 0).toString();
        String value1 = jTableProduct.getValueAt(i, 1).toString();
        String value2 = jTableProduct.getValueAt(i, 2).toString();
        String value3 = jTableProduct.getValueAt(i, 3).toString();

        txtProductName4.setText(value);
        if (value1.equals("Ăn vặt")) {
            jComboBox1.setSelectedIndex(0);
        } else if (value1.equals("Sữa tươi")) {
            jComboBox1.setSelectedIndex(1);
        } else {
            jComboBox1.setSelectedIndex(2);
        }
        txtAmountRemaining4.setText(value2);
        txtPrice4.setText(value3);

    }//GEN-LAST:event_jTableProductMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        showDuLieuProduct();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
        jTableProduct.setModel(new DefaultTableModel(null, new Object[]{"Mã sản phẩm", "Tên Sản Phẩm", "Số Lượng", "Giá"}));
        findProduct(jTableProduct, jTextField2.getText());
    }//GEN-LAST:event_jTextField2KeyReleased

    private void btnSkip3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkip3ActionPerformed
        // TODO add your handling code here:
        jDialog3.setVisible(false);
    }//GEN-LAST:event_btnSkip3ActionPerformed

    private void btnSkip4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkip4ActionPerformed
        // TODO add your handling code here:
        jDialog4.setVisible(false);
    }//GEN-LAST:event_btnSkip4ActionPerformed
    private void showDuLieuProduct() {
        try {
            jTableProduct.removeAll();
            String[] arr = {"Mã sản phẩm", "Tên sản phẩm", "Số Lượng", "Giá"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);
            String query = "select p.productName,p.productID,p.amountRemaining,p.price from products p INNER JOIN productType t ON p.productTypeID=t.productTypeID";
            Connection connection = ConnectionDB.getConnection();
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector vector = new Vector();
                vector.add(rs.getString("productID"));
                vector.add(rs.getString("productName"));
                vector.add(rs.getInt("amountRemaining"));
                vector.add(rs.getInt("price"));
                model.addRow(vector);
            }
            jTableProduct.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(JPanelOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void findProduct(JTable table, String valueToSearch) {
        try {
            Connection con = ConnectionDB.getConnection();
            PreparedStatement ps;
            ps = con.prepareStatement("select p.productID,p.productName,p.amountRemaining,p.price"
                    + " from products p INNER JOIN productType t ON p.productTypeID=t.productTypeID where p.productName LIKE ?");
            ps.setString(1, "%" + valueToSearch + "%");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) table.getModel();

            Object[] row;

            while (rs.next()) {
                row = new Object[4];
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getInt(3);
                row[3] = rs.getString(4);

                model.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JPanelProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void showAllTypeProductComboBox() throws SQLException {
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        String query = " select distinct productTypeName from productType";
        Connection connection = ConnectionDB.getConnection();
        PreparedStatement ps = connection.prepareStatement(query);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            String type = rs.getString("productTypeName");
            jComboBox1.addItem(type);
            jComboBox2.addItem(type);
        }
        rs.close();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd3;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnAddType;
    private javax.swing.JButton btnDialogType;
    private javax.swing.JButton btnDialogType1;
    private javax.swing.JButton btnEdit4;
    private javax.swing.JButton btnEditProduct;
    private javax.swing.JButton btnEditType;
    private javax.swing.JButton btnSkip3;
    private javax.swing.JButton btnSkip4;
    private javax.swing.JButton btnSkipDialog;
    private javax.swing.JButton btnSkipDialog1;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProduct;
    private javax.swing.JTable jTableProductType;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtAmountRemaining3;
    private javax.swing.JTextField txtAmountRemaining4;
    private javax.swing.JTextField txtPrice3;
    private javax.swing.JTextField txtPrice4;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName3;
    private javax.swing.JTextField txtProductName4;
    private javax.swing.JTextField txtProductTypeID;
    private javax.swing.JTextField txtProductTypeID1;
    private javax.swing.JTextField txtProductTypeName;
    private javax.swing.JTextField txtProductTypeName1;
    // End of variables declaration//GEN-END:variables

}
